# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11measurement.proto\x12\x05\x63\x65\x64ri\"\x9e\x02\n\rSensorReading\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x10\n\x08volume_l\x18\x03 \x01(\x02\x12\x11\n\tsensor_id\x18\x04 \x01(\r\x12\x16\n\x0eheater_profile\x18\x05 \x01(\t\x12\x18\n\x10measurement_step\x18\x06 \x01(\r\x12\x0e\n\x06temp_c\x18\x07 \x01(\x02\x12\x14\n\x0chumidity_pct\x18\x08 \x01(\x02\x12\x14\n\x0cpressure_hpa\x18\t \x01(\x02\x12\x1a\n\x12gas_resistance_ohm\x18\n \x01(\r\x12\x11\n\tgas_valid\x18\x0b \x01(\x08\x12\x13\n\x0bheat_stable\x18\x0c \x01(\x08\x12\x11\n\ttimestamp\x18\r \x01(\x04\"<\n\x12SensorReadingBatch\x12&\n\x08readings\x18\x01 \x03(\x0b\x32\x14.cedri.SensorReadingb\x06proto3')



_SENSORREADING = DESCRIPTOR.message_types_by_name['SensorReading']
_SENSORREADINGBATCH = DESCRIPTOR.message_types_by_name['SensorReadingBatch']
SensorReading = _reflection.GeneratedProtocolMessageType('SensorReading', (_message.Message,), {
  'DESCRIPTOR' : _SENSORREADING,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:cedri.SensorReading)
  })
_sym_db.RegisterMessage(SensorReading)

SensorReadingBatch = _reflection.GeneratedProtocolMessageType('SensorReadingBatch', (_message.Message,), {
  'DESCRIPTOR' : _SENSORREADINGBATCH,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:cedri.SensorReadingBatch)
  })
_sym_db.RegisterMessage(SensorReadingBatch)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORREADING._serialized_start=29
  _SENSORREADING._serialized_end=315
  _SENSORREADINGBATCH._serialized_start=317
  _SENSORREADINGBATCH._serialized_end=377
# @@protoc_insertion_point(module_scope)
