# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11measurement.proto\x12\x05\x63\x65\x64ri\"\xf1\x03\n\x10SensorGpsReading\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x13\n\x0blocation_id\x18\x02 \x01(\r\x12\x11\n\tsensor_id\x18\x03 \x01(\r\x12,\n\x0eheater_profile\x18\x04 \x01(\x0e\x32\x14.cedri.HeaterProfile\x12\x18\n\x10measurement_step\x18\x05 \x01(\r\x12\x0e\n\x06temp_c\x18\x06 \x01(\x02\x12\x14\n\x0chumidity_pct\x18\x07 \x01(\x02\x12\x14\n\x0cpressure_hpa\x18\x08 \x01(\x02\x12\x1a\n\x12gas_resistance_ohm\x18\t \x01(\r\x12\x11\n\tgas_valid\x18\n \x01(\x08\x12\x13\n\x0bheat_stable\x18\x0b \x01(\x08\x12\x11\n\ttimestamp\x18\x0c \x01(\r\x12\x10\n\x08latitude\x18\r \x01(\x02\x12\x11\n\tlongitude\x18\x0e \x01(\x02\x12\x10\n\x08volume_l\x18\x0f \x01(\x02\x12\x13\n\x0btotal_steps\x18\x10 \x01(\r\x12\x16\n\x0estep_window_ms\x18\x11 \x01(\r\x12\x17\n\x0f\x63ycle_period_ms\x18\x12 \x01(\r\x12\x13\n\x0b\x63ycle_index\x18\x13 \x01(\r\x12\x19\n\x11heater_setpoint_c\x18\x14 \x01(\x02\x12\x1a\n\x12heater_duration_ms\x18\x15 \x01(\r*o\n\rHeaterProfile\x12\n\n\x06HP_411\x10\x00\x12\n\n\x06HP_412\x10\x01\x12\n\n\x06HP_413\x10\x02\x12\n\n\x06HP_414\x10\x03\x12\n\n\x06HP_501\x10\x04\x12\n\n\x06HP_502\x10\x05\x12\n\n\x06HP_503\x10\x06\x12\n\n\x06HP_504\x10\x07\x62\x06proto3')

_HEATERPROFILE = DESCRIPTOR.enum_types_by_name['HeaterProfile']
HeaterProfile = enum_type_wrapper.EnumTypeWrapper(_HEATERPROFILE)
HP_411 = 0
HP_412 = 1
HP_413 = 2
HP_414 = 3
HP_501 = 4
HP_502 = 5
HP_503 = 6
HP_504 = 7


_SENSORGPSREADING = DESCRIPTOR.message_types_by_name['SensorGpsReading']
SensorGpsReading = _reflection.GeneratedProtocolMessageType('SensorGpsReading', (_message.Message,), {
  'DESCRIPTOR' : _SENSORGPSREADING,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:cedri.SensorGpsReading)
  })
_sym_db.RegisterMessage(SensorGpsReading)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEATERPROFILE._serialized_start=528
  _HEATERPROFILE._serialized_end=639
  _SENSORGPSREADING._serialized_start=29
  _SENSORGPSREADING._serialized_end=526
# @@protoc_insertion_point(module_scope)
