# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11measurement.proto\x12\x05\x63\x65\x64ri\"\xa9\x02\n\x11SensorReadingLite\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x13\n\x0blocation_id\x18\x02 \x01(\r\x12\x11\n\tsensor_id\x18\x03 \x01(\r\x12,\n\x0eheater_profile\x18\x04 \x01(\x0e\x32\x14.cedri.HeaterProfile\x12\x18\n\x10measurement_step\x18\x05 \x01(\r\x12\x0e\n\x06temp_c\x18\x06 \x01(\x02\x12\x14\n\x0chumidity_pct\x18\x07 \x01(\x02\x12\x14\n\x0cpressure_hpa\x18\x08 \x01(\x02\x12\x1a\n\x12gas_resistance_ohm\x18\t \x01(\r\x12\x11\n\tgas_valid\x18\n \x01(\x08\x12\x13\n\x0bheat_stable\x18\x0b \x01(\x08\x12\x11\n\ttimestamp\x18\x0c \x01(\r\"k\n\nGpsReading\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\r\x12\x12\n\nsatellites\x18\x05 \x01(\r*o\n\rHeaterProfile\x12\n\n\x06HP_354\x10\x00\x12\n\n\x06HP_301\x10\x01\x12\n\n\x06HP_321\x10\x02\x12\n\n\x06HP_322\x10\x03\x12\n\n\x06HP_323\x10\x04\x12\n\n\x06HP_324\x10\x05\x12\n\n\x06HP_331\x10\x06\x12\n\n\x06HP_332\x10\x07\x62\x06proto3')

_HEATERPROFILE = DESCRIPTOR.enum_types_by_name['HeaterProfile']
HeaterProfile = enum_type_wrapper.EnumTypeWrapper(_HEATERPROFILE)
HP_354 = 0
HP_301 = 1
HP_321 = 2
HP_322 = 3
HP_323 = 4
HP_324 = 5
HP_331 = 6
HP_332 = 7


_SENSORREADINGLITE = DESCRIPTOR.message_types_by_name['SensorReadingLite']
_GPSREADING = DESCRIPTOR.message_types_by_name['GpsReading']
SensorReadingLite = _reflection.GeneratedProtocolMessageType('SensorReadingLite', (_message.Message,), {
  'DESCRIPTOR' : _SENSORREADINGLITE,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:cedri.SensorReadingLite)
  })
_sym_db.RegisterMessage(SensorReadingLite)

GpsReading = _reflection.GeneratedProtocolMessageType('GpsReading', (_message.Message,), {
  'DESCRIPTOR' : _GPSREADING,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:cedri.GpsReading)
  })
_sym_db.RegisterMessage(GpsReading)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEATERPROFILE._serialized_start=437
  _HEATERPROFILE._serialized_end=548
  _SENSORREADINGLITE._serialized_start=29
  _SENSORREADINGLITE._serialized_end=326
  _GPSREADING._serialized_start=328
  _GPSREADING._serialized_end=435
# @@protoc_insertion_point(module_scope)
