/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "measurement.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cedri_SensorReading, cedri_SensorReading, AUTO)


PB_BIND(cedri_VOCReading, cedri_VOCReading, AUTO)





